version: 1.0.{build}
build_script:
- cmd: >-
    git submodule update --init --recursive
    
    cd build

    cmake ../ -G "Visual Studio 14 2015 Win64" -DBOOST_ROOT=C:\Libraries\boost_1_67_0

    cmake --build ../build
test_script:
- cmd: >-
    ctest -VV -C Debug 
    
    curl -F 'file=test.xml' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID" -v
