version: 1.0.{build}
build_script:
- cmd: >-
    git submodule update --init --recursive
    
    cd 7zip-cpp

    cmake ../ -G "Visual Studio 15 2017 Win64" -DBOOST_ROOT=C:\Libraries\boost_1_67_0

    cmake --build ../build --target 7zpp
test_script:
- cmd: >-
    cmake --build ../build --target TestApp

    ctest -VV -C Debug
